name: JPMS Test Build Workflow

run-name: 'Test Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  workflow_call:


jobs:
  build-job:
    name: Build Job -- ${{matrix.repos}}
    strategy:
      # max-parallel: 1
      matrix:
        repos:
          - activej-bytebuf
          # - activej-common
          - antlr4-runtime
          - auto-service
          - bugsplat
          - directory-watcher
          - eclipse-collections-api
          - eclipse-collections
          - guava
          - hapi-fhir-base
          - hapi-fhir-caching-api
          - hapi-fhir-r4
          - hapi-fhir-structures-r4
          - hapi-fhir-utilities
          - httpclient
          - httpcore
          - httpmime
          - javax-inject
          - jgit
          - jheaps
          - jsr305
          - mvstore
          - ontology-model
          - protobuf-java
          - record-builder-core
          - roaringbitmap
          - snorocket
    runs-on: ubuntu-24.04
    steps:
     - name: Test Build JPMS Repos
       uses: ikmdev/maven-jpms-test-build-action@main
       with:
         repo_name: ${{matrix.repos}}
