name: JPMS Test Build Workflow

run-name: 'Test Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  workflow_call:


jobs:
  build-job:
    name: Build Job -- ${{matrix.repos}}
    strategy:
      matrix:
        repos:
          - activej-bytebuf
          - activej-common
          - antlr4-runtime
          - auto-service
          - bugsplat
          - directory-watcher
          - eclipse-collections-api
          - eclipse-collections
          - httpclient
          # - httpclient5
          - httpcore
          - httpcore5
          - httpcore5-h2
          - httpmime
          - javax-inject
          - jgit
          - jheaps
          - jsr305
          - mvstore
          - ontology-model
          - protobuf-java
          - record-builder-core
          - snorocket
          - spotbugs-annotation
    runs-on: ubuntu-24.04
    steps:
     - name: Test Build JPMS Repos
       uses: ikmdev/maven-jpms-test-build-action@main
       with:
         repo_name: ${{matrix.repos}}
